'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace WSPSA4
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PersonaServiceA4SoapBinding", [Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class PersonaServiceA4
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private dummyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getPersonaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.PrototipoAfip.My.MySettings.Default.PrototipoAfip_WSPSA4_PersonaServiceA4
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event dummyCompleted As dummyCompletedEventHandler
        
        '''<remarks/>
        Public Event getPersonaCompleted As getPersonaCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://a4.soap.ws.server.puc.sr/", ResponseNamespace:="http://a4.soap.ws.server.puc.sr/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function dummy() As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> dummyReturn
            Dim results() As Object = Me.Invoke("dummy", New Object(-1) {})
            Return CType(results(0),dummyReturn)
        End Function
        
        '''<remarks/>
        Public Overloads Sub dummyAsync()
            Me.dummyAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub dummyAsync(ByVal userState As Object)
            If (Me.dummyOperationCompleted Is Nothing) Then
                Me.dummyOperationCompleted = AddressOf Me.OndummyOperationCompleted
            End If
            Me.InvokeAsync("dummy", New Object(-1) {}, Me.dummyOperationCompleted, userState)
        End Sub
        
        Private Sub OndummyOperationCompleted(ByVal arg As Object)
            If (Not (Me.dummyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent dummyCompleted(Me, New dummyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://a4.soap.ws.server.puc.sr/", ResponseNamespace:="http://a4.soap.ws.server.puc.sr/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getPersona(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal token As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal sign As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal cuitRepresentada As Long, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal idPersona As Long) As <System.Xml.Serialization.XmlElementAttribute("personaReturn", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> personaReturn
            Dim results() As Object = Me.Invoke("getPersona", New Object() {token, sign, cuitRepresentada, idPersona})
            Return CType(results(0),personaReturn)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getPersonaAsync(ByVal token As String, ByVal sign As String, ByVal cuitRepresentada As Long, ByVal idPersona As Long)
            Me.getPersonaAsync(token, sign, cuitRepresentada, idPersona, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getPersonaAsync(ByVal token As String, ByVal sign As String, ByVal cuitRepresentada As Long, ByVal idPersona As Long, ByVal userState As Object)
            If (Me.getPersonaOperationCompleted Is Nothing) Then
                Me.getPersonaOperationCompleted = AddressOf Me.OngetPersonaOperationCompleted
            End If
            Me.InvokeAsync("getPersona", New Object() {token, sign, cuitRepresentada, idPersona}, Me.getPersonaOperationCompleted, userState)
        End Sub
        
        Private Sub OngetPersonaOperationCompleted(ByVal arg As Object)
            If (Not (Me.getPersonaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getPersonaCompleted(Me, New getPersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class dummyReturn
        
        Private appserverField As String
        
        Private authserverField As String
        
        Private dbserverField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property appserver() As String
            Get
                Return Me.appserverField
            End Get
            Set
                Me.appserverField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property authserver() As String
            Get
                Return Me.authserverField
            End Get
            Set
                Me.authserverField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property dbserver() As String
            Get
                Return Me.dbserverField
            End Get
            Set
                Me.dbserverField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class telefono
        
        Private numeroField As Long
        
        Private numeroFieldSpecified As Boolean
        
        Private tipoLineaField As String
        
        Private tipoTelefonoField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numero() As Long
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property numeroSpecified() As Boolean
            Get
                Return Me.numeroFieldSpecified
            End Get
            Set
                Me.numeroFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoLinea() As String
            Get
                Return Me.tipoLineaField
            End Get
            Set
                Me.tipoLineaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoTelefono() As String
            Get
                Return Me.tipoTelefonoField
            End Get
            Set
                Me.tipoTelefonoField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class relacion
        
        Private ffRelacionField As Date
        
        Private ffRelacionFieldSpecified As Boolean
        
        Private ffVencimientoField As Date
        
        Private ffVencimientoFieldSpecified As Boolean
        
        Private idPersonaField As Long
        
        Private idPersonaFieldSpecified As Boolean
        
        Private idPersonaAsociadaField As Long
        
        Private idPersonaAsociadaFieldSpecified As Boolean
        
        Private subtipoRelacionField As String
        
        Private tipoRelacionField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ffRelacion() As Date
            Get
                Return Me.ffRelacionField
            End Get
            Set
                Me.ffRelacionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ffRelacionSpecified() As Boolean
            Get
                Return Me.ffRelacionFieldSpecified
            End Get
            Set
                Me.ffRelacionFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ffVencimiento() As Date
            Get
                Return Me.ffVencimientoField
            End Get
            Set
                Me.ffVencimientoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ffVencimientoSpecified() As Boolean
            Get
                Return Me.ffVencimientoFieldSpecified
            End Get
            Set
                Me.ffVencimientoFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idPersona() As Long
            Get
                Return Me.idPersonaField
            End Get
            Set
                Me.idPersonaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idPersonaSpecified() As Boolean
            Get
                Return Me.idPersonaFieldSpecified
            End Get
            Set
                Me.idPersonaFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idPersonaAsociada() As Long
            Get
                Return Me.idPersonaAsociadaField
            End Get
            Set
                Me.idPersonaAsociadaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idPersonaAsociadaSpecified() As Boolean
            Get
                Return Me.idPersonaAsociadaFieldSpecified
            End Get
            Set
                Me.idPersonaAsociadaFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property subtipoRelacion() As String
            Get
                Return Me.subtipoRelacionField
            End Get
            Set
                Me.subtipoRelacionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoRelacion() As String
            Get
                Return Me.tipoRelacionField
            End Get
            Set
                Me.tipoRelacionField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class regimen
        
        Private descripcionRegimenField As String
        
        Private diaPeriodoField As Integer
        
        Private diaPeriodoFieldSpecified As Boolean
        
        Private estadoField As String
        
        Private idImpuestoField As Integer
        
        Private idImpuestoFieldSpecified As Boolean
        
        Private idRegimenField As Integer
        
        Private idRegimenFieldSpecified As Boolean
        
        Private periodoField As Integer
        
        Private periodoFieldSpecified As Boolean
        
        Private tipoRegimenField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcionRegimen() As String
            Get
                Return Me.descripcionRegimenField
            End Get
            Set
                Me.descripcionRegimenField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property diaPeriodo() As Integer
            Get
                Return Me.diaPeriodoField
            End Get
            Set
                Me.diaPeriodoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property diaPeriodoSpecified() As Boolean
            Get
                Return Me.diaPeriodoFieldSpecified
            End Get
            Set
                Me.diaPeriodoFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idImpuesto() As Integer
            Get
                Return Me.idImpuestoField
            End Get
            Set
                Me.idImpuestoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idImpuestoSpecified() As Boolean
            Get
                Return Me.idImpuestoFieldSpecified
            End Get
            Set
                Me.idImpuestoFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idRegimen() As Integer
            Get
                Return Me.idRegimenField
            End Get
            Set
                Me.idRegimenField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idRegimenSpecified() As Boolean
            Get
                Return Me.idRegimenFieldSpecified
            End Get
            Set
                Me.idRegimenFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property periodo() As Integer
            Get
                Return Me.periodoField
            End Get
            Set
                Me.periodoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property periodoSpecified() As Boolean
            Get
                Return Me.periodoFieldSpecified
            End Get
            Set
                Me.periodoFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoRegimen() As String
            Get
                Return Me.tipoRegimenField
            End Get
            Set
                Me.tipoRegimenField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class impuesto
        
        Private descripcionImpuestoField As String
        
        Private diaPeriodoField As Integer
        
        Private diaPeriodoFieldSpecified As Boolean
        
        Private estadoField As String
        
        Private ffInscripcionField As Date
        
        Private ffInscripcionFieldSpecified As Boolean
        
        Private idImpuestoField As Integer
        
        Private idImpuestoFieldSpecified As Boolean
        
        Private periodoField As Integer
        
        Private periodoFieldSpecified As Boolean
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcionImpuesto() As String
            Get
                Return Me.descripcionImpuestoField
            End Get
            Set
                Me.descripcionImpuestoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property diaPeriodo() As Integer
            Get
                Return Me.diaPeriodoField
            End Get
            Set
                Me.diaPeriodoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property diaPeriodoSpecified() As Boolean
            Get
                Return Me.diaPeriodoFieldSpecified
            End Get
            Set
                Me.diaPeriodoFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ffInscripcion() As Date
            Get
                Return Me.ffInscripcionField
            End Get
            Set
                Me.ffInscripcionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ffInscripcionSpecified() As Boolean
            Get
                Return Me.ffInscripcionFieldSpecified
            End Get
            Set
                Me.ffInscripcionFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idImpuesto() As Integer
            Get
                Return Me.idImpuestoField
            End Get
            Set
                Me.idImpuestoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idImpuestoSpecified() As Boolean
            Get
                Return Me.idImpuestoFieldSpecified
            End Get
            Set
                Me.idImpuestoFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property periodo() As Integer
            Get
                Return Me.periodoField
            End Get
            Set
                Me.periodoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property periodoSpecified() As Boolean
            Get
                Return Me.periodoFieldSpecified
            End Get
            Set
                Me.periodoFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class email
        
        Private direccionField As String
        
        Private estadoField As String
        
        Private tipoEmailField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property direccion() As String
            Get
                Return Me.direccionField
            End Get
            Set
                Me.direccionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoEmail() As String
            Get
                Return Me.tipoEmailField
            End Get
            Set
                Me.tipoEmailField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class domicilio
        
        Private codPostalField As String
        
        Private datoAdicionalField As String
        
        Private descripcionProvinciaField As String
        
        Private direccionField As String
        
        Private idProvinciaField As Integer
        
        Private idProvinciaFieldSpecified As Boolean
        
        Private localidadField As String
        
        Private tipoDatoAdicionalField As String
        
        Private tipoDomicilioField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codPostal() As String
            Get
                Return Me.codPostalField
            End Get
            Set
                Me.codPostalField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property datoAdicional() As String
            Get
                Return Me.datoAdicionalField
            End Get
            Set
                Me.datoAdicionalField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcionProvincia() As String
            Get
                Return Me.descripcionProvinciaField
            End Get
            Set
                Me.descripcionProvinciaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property direccion() As String
            Get
                Return Me.direccionField
            End Get
            Set
                Me.direccionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idProvincia() As Integer
            Get
                Return Me.idProvinciaField
            End Get
            Set
                Me.idProvinciaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idProvinciaSpecified() As Boolean
            Get
                Return Me.idProvinciaFieldSpecified
            End Get
            Set
                Me.idProvinciaFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property localidad() As String
            Get
                Return Me.localidadField
            End Get
            Set
                Me.localidadField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoDatoAdicional() As String
            Get
                Return Me.tipoDatoAdicionalField
            End Get
            Set
                Me.tipoDatoAdicionalField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoDomicilio() As String
            Get
                Return Me.tipoDomicilioField
            End Get
            Set
                Me.tipoDomicilioField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class dependencia
        
        Private descripcionDependenciaField As String
        
        Private idDependenciaField As Integer
        
        Private idDependenciaFieldSpecified As Boolean
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcionDependencia() As String
            Get
                Return Me.descripcionDependenciaField
            End Get
            Set
                Me.descripcionDependenciaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idDependencia() As Integer
            Get
                Return Me.idDependenciaField
            End Get
            Set
                Me.idDependenciaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idDependenciaSpecified() As Boolean
            Get
                Return Me.idDependenciaFieldSpecified
            End Get
            Set
                Me.idDependenciaFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class categoria
        
        Private descripcionCategoriaField As String
        
        Private estadoField As String
        
        Private idCategoriaField As Integer
        
        Private idCategoriaFieldSpecified As Boolean
        
        Private idImpuestoField As Integer
        
        Private idImpuestoFieldSpecified As Boolean
        
        Private periodoField As Integer
        
        Private periodoFieldSpecified As Boolean
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcionCategoria() As String
            Get
                Return Me.descripcionCategoriaField
            End Get
            Set
                Me.descripcionCategoriaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idCategoria() As Integer
            Get
                Return Me.idCategoriaField
            End Get
            Set
                Me.idCategoriaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idCategoriaSpecified() As Boolean
            Get
                Return Me.idCategoriaFieldSpecified
            End Get
            Set
                Me.idCategoriaFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idImpuesto() As Integer
            Get
                Return Me.idImpuestoField
            End Get
            Set
                Me.idImpuestoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idImpuestoSpecified() As Boolean
            Get
                Return Me.idImpuestoFieldSpecified
            End Get
            Set
                Me.idImpuestoFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property periodo() As Integer
            Get
                Return Me.periodoField
            End Get
            Set
                Me.periodoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property periodoSpecified() As Boolean
            Get
                Return Me.periodoFieldSpecified
            End Get
            Set
                Me.periodoFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class actividad
        
        Private descripcionActividadField As String
        
        Private idActividadField As Long
        
        Private idActividadFieldSpecified As Boolean
        
        Private nomencladorField As Integer
        
        Private nomencladorFieldSpecified As Boolean
        
        Private ordenField As Integer
        
        Private ordenFieldSpecified As Boolean
        
        Private periodoField As Integer
        
        Private periodoFieldSpecified As Boolean
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property descripcionActividad() As String
            Get
                Return Me.descripcionActividadField
            End Get
            Set
                Me.descripcionActividadField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idActividad() As Long
            Get
                Return Me.idActividadField
            End Get
            Set
                Me.idActividadField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idActividadSpecified() As Boolean
            Get
                Return Me.idActividadFieldSpecified
            End Get
            Set
                Me.idActividadFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nomenclador() As Integer
            Get
                Return Me.nomencladorField
            End Get
            Set
                Me.nomencladorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property nomencladorSpecified() As Boolean
            Get
                Return Me.nomencladorFieldSpecified
            End Get
            Set
                Me.nomencladorFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property orden() As Integer
            Get
                Return Me.ordenField
            End Get
            Set
                Me.ordenField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ordenSpecified() As Boolean
            Get
                Return Me.ordenFieldSpecified
            End Get
            Set
                Me.ordenFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property periodo() As Integer
            Get
                Return Me.periodoField
            End Get
            Set
                Me.periodoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property periodoSpecified() As Boolean
            Get
                Return Me.periodoFieldSpecified
            End Get
            Set
                Me.periodoFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class persona
        
        Private actividadField() As actividad
        
        Private apellidoField As String
        
        Private cantidadSociosEmpresaMonoField As Integer
        
        Private cantidadSociosEmpresaMonoFieldSpecified As Boolean
        
        Private categoriaField() As categoria
        
        Private claveInactivaAsociadaField() As System.Nullable(Of Long)
        
        Private dependenciaField As dependencia
        
        Private domicilioField() As domicilio
        
        Private emailField() As email
        
        Private estadoClaveField As String
        
        Private fechaContratoSocialField As Date
        
        Private fechaContratoSocialFieldSpecified As Boolean
        
        Private fechaFallecimientoField As Date
        
        Private fechaFallecimientoFieldSpecified As Boolean
        
        Private fechaInscripcionField As Date
        
        Private fechaInscripcionFieldSpecified As Boolean
        
        Private fechaJubiladoField As Date
        
        Private fechaJubiladoFieldSpecified As Boolean
        
        Private fechaNacimientoField As Date
        
        Private fechaNacimientoFieldSpecified As Boolean
        
        Private fechaVencimientoMigracionField As Date
        
        Private fechaVencimientoMigracionFieldSpecified As Boolean
        
        Private formaJuridicaField As String
        
        Private idPersonaField As Long
        
        Private idPersonaFieldSpecified As Boolean
        
        Private impuestoField() As impuesto
        
        Private leyJubilacionField As Integer
        
        Private leyJubilacionFieldSpecified As Boolean
        
        Private localidadInscripcionField As String
        
        Private mesCierreField As Integer
        
        Private mesCierreFieldSpecified As Boolean
        
        Private nombreField As String
        
        Private numeroDocumentoField As String
        
        Private numeroInscripcionField As Long
        
        Private numeroInscripcionFieldSpecified As Boolean
        
        Private organismoInscripcionField As String
        
        Private organismoOriginanteField As String
        
        Private porcentajeCapitalNacionalField As Double
        
        Private porcentajeCapitalNacionalFieldSpecified As Boolean
        
        Private provinciaInscripcionField As String
        
        Private razonSocialField As String
        
        Private regimenField() As regimen
        
        Private relacionField() As relacion
        
        Private sexoField As String
        
        Private telefonoField() As telefono
        
        Private tipoClaveField As String
        
        Private tipoDocumentoField As String
        
        Private tipoOrganismoOriginanteField As String
        
        Private tipoPersonaField As String
        
        Private tipoResidenciaField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("actividad", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property actividad() As actividad()
            Get
                Return Me.actividadField
            End Get
            Set
                Me.actividadField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property apellido() As String
            Get
                Return Me.apellidoField
            End Get
            Set
                Me.apellidoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property cantidadSociosEmpresaMono() As Integer
            Get
                Return Me.cantidadSociosEmpresaMonoField
            End Get
            Set
                Me.cantidadSociosEmpresaMonoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property cantidadSociosEmpresaMonoSpecified() As Boolean
            Get
                Return Me.cantidadSociosEmpresaMonoFieldSpecified
            End Get
            Set
                Me.cantidadSociosEmpresaMonoFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("categoria", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property categoria() As categoria()
            Get
                Return Me.categoriaField
            End Get
            Set
                Me.categoriaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("claveInactivaAsociada", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property claveInactivaAsociada() As System.Nullable(Of Long)()
            Get
                Return Me.claveInactivaAsociadaField
            End Get
            Set
                Me.claveInactivaAsociadaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property dependencia() As dependencia
            Get
                Return Me.dependenciaField
            End Get
            Set
                Me.dependenciaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("domicilio", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property domicilio() As domicilio()
            Get
                Return Me.domicilioField
            End Get
            Set
                Me.domicilioField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("email", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property email() As email()
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property estadoClave() As String
            Get
                Return Me.estadoClaveField
            End Get
            Set
                Me.estadoClaveField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fechaContratoSocial() As Date
            Get
                Return Me.fechaContratoSocialField
            End Get
            Set
                Me.fechaContratoSocialField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaContratoSocialSpecified() As Boolean
            Get
                Return Me.fechaContratoSocialFieldSpecified
            End Get
            Set
                Me.fechaContratoSocialFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fechaFallecimiento() As Date
            Get
                Return Me.fechaFallecimientoField
            End Get
            Set
                Me.fechaFallecimientoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaFallecimientoSpecified() As Boolean
            Get
                Return Me.fechaFallecimientoFieldSpecified
            End Get
            Set
                Me.fechaFallecimientoFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fechaInscripcion() As Date
            Get
                Return Me.fechaInscripcionField
            End Get
            Set
                Me.fechaInscripcionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaInscripcionSpecified() As Boolean
            Get
                Return Me.fechaInscripcionFieldSpecified
            End Get
            Set
                Me.fechaInscripcionFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fechaJubilado() As Date
            Get
                Return Me.fechaJubiladoField
            End Get
            Set
                Me.fechaJubiladoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaJubiladoSpecified() As Boolean
            Get
                Return Me.fechaJubiladoFieldSpecified
            End Get
            Set
                Me.fechaJubiladoFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fechaNacimiento() As Date
            Get
                Return Me.fechaNacimientoField
            End Get
            Set
                Me.fechaNacimientoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaNacimientoSpecified() As Boolean
            Get
                Return Me.fechaNacimientoFieldSpecified
            End Get
            Set
                Me.fechaNacimientoFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fechaVencimientoMigracion() As Date
            Get
                Return Me.fechaVencimientoMigracionField
            End Get
            Set
                Me.fechaVencimientoMigracionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaVencimientoMigracionSpecified() As Boolean
            Get
                Return Me.fechaVencimientoMigracionFieldSpecified
            End Get
            Set
                Me.fechaVencimientoMigracionFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property formaJuridica() As String
            Get
                Return Me.formaJuridicaField
            End Get
            Set
                Me.formaJuridicaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property idPersona() As Long
            Get
                Return Me.idPersonaField
            End Get
            Set
                Me.idPersonaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property idPersonaSpecified() As Boolean
            Get
                Return Me.idPersonaFieldSpecified
            End Get
            Set
                Me.idPersonaFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("impuesto", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property impuesto() As impuesto()
            Get
                Return Me.impuestoField
            End Get
            Set
                Me.impuestoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property leyJubilacion() As Integer
            Get
                Return Me.leyJubilacionField
            End Get
            Set
                Me.leyJubilacionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property leyJubilacionSpecified() As Boolean
            Get
                Return Me.leyJubilacionFieldSpecified
            End Get
            Set
                Me.leyJubilacionFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property localidadInscripcion() As String
            Get
                Return Me.localidadInscripcionField
            End Get
            Set
                Me.localidadInscripcionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mesCierre() As Integer
            Get
                Return Me.mesCierreField
            End Get
            Set
                Me.mesCierreField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property mesCierreSpecified() As Boolean
            Get
                Return Me.mesCierreFieldSpecified
            End Get
            Set
                Me.mesCierreFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numeroDocumento() As String
            Get
                Return Me.numeroDocumentoField
            End Get
            Set
                Me.numeroDocumentoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property numeroInscripcion() As Long
            Get
                Return Me.numeroInscripcionField
            End Get
            Set
                Me.numeroInscripcionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property numeroInscripcionSpecified() As Boolean
            Get
                Return Me.numeroInscripcionFieldSpecified
            End Get
            Set
                Me.numeroInscripcionFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property organismoInscripcion() As String
            Get
                Return Me.organismoInscripcionField
            End Get
            Set
                Me.organismoInscripcionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property organismoOriginante() As String
            Get
                Return Me.organismoOriginanteField
            End Get
            Set
                Me.organismoOriginanteField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property porcentajeCapitalNacional() As Double
            Get
                Return Me.porcentajeCapitalNacionalField
            End Get
            Set
                Me.porcentajeCapitalNacionalField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property porcentajeCapitalNacionalSpecified() As Boolean
            Get
                Return Me.porcentajeCapitalNacionalFieldSpecified
            End Get
            Set
                Me.porcentajeCapitalNacionalFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property provinciaInscripcion() As String
            Get
                Return Me.provinciaInscripcionField
            End Get
            Set
                Me.provinciaInscripcionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property razonSocial() As String
            Get
                Return Me.razonSocialField
            End Get
            Set
                Me.razonSocialField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("regimen", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property regimen() As regimen()
            Get
                Return Me.regimenField
            End Get
            Set
                Me.regimenField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("relacion", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property relacion() As relacion()
            Get
                Return Me.relacionField
            End Get
            Set
                Me.relacionField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property sexo() As String
            Get
                Return Me.sexoField
            End Get
            Set
                Me.sexoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute("telefono", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property telefono() As telefono()
            Get
                Return Me.telefonoField
            End Get
            Set
                Me.telefonoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoClave() As String
            Get
                Return Me.tipoClaveField
            End Get
            Set
                Me.tipoClaveField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoDocumento() As String
            Get
                Return Me.tipoDocumentoField
            End Get
            Set
                Me.tipoDocumentoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoOrganismoOriginante() As String
            Get
                Return Me.tipoOrganismoOriginanteField
            End Get
            Set
                Me.tipoOrganismoOriginanteField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoPersona() As String
            Get
                Return Me.tipoPersonaField
            End Get
            Set
                Me.tipoPersonaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property tipoResidencia() As String
            Get
                Return Me.tipoResidenciaField
            End Get
            Set
                Me.tipoResidenciaField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class metadata
        
        Private fechaHoraField As Date
        
        Private fechaHoraFieldSpecified As Boolean
        
        Private servidorField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property fechaHora() As Date
            Get
                Return Me.fechaHoraField
            End Get
            Set
                Me.fechaHoraField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaHoraSpecified() As Boolean
            Get
                Return Me.fechaHoraFieldSpecified
            End Get
            Set
                Me.fechaHoraFieldSpecified = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property servidor() As String
            Get
                Return Me.servidorField
            End Get
            Set
                Me.servidorField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://a4.soap.ws.server.puc.sr/")>  _
    Partial Public Class personaReturn
        
        Private metadataField As metadata
        
        Private personaField As persona
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property metadata() As metadata
            Get
                Return Me.metadataField
            End Get
            Set
                Me.metadataField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property persona() As persona
            Get
                Return Me.personaField
            End Get
            Set
                Me.personaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub dummyCompletedEventHandler(ByVal sender As Object, ByVal e As dummyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class dummyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As dummyReturn
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),dummyReturn)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")>  _
    Public Delegate Sub getPersonaCompletedEventHandler(ByVal sender As Object, ByVal e As getPersonaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getPersonaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As personaReturn
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),personaReturn)
            End Get
        End Property
    End Class
End Namespace
